name: Jonathan Elijah
favicon: null
layout_spectrum: 0.963051859755069
typography_spectrum: 0.8293467366602272
title: Jonathan Elijah
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.367971332045272
  lightness: 0.6497134168166667
  saturation: 0.26399172423407435
  rhythmicContrast: 0.6849700319580734
purpose: []
